# -- 코드를 입력하세요
# SELECT AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(PRICE*CNT) AS TOTAL_SALES
# FROM (
#     SELECT A.AUTHOR_ID, B.AUTHOR_NAME, A.CATEGORY, A.BOOK_ID, A.PRICE
#     FROM BOOK AS A
#     JOIN AUTHOR AS B
#     ON A.AUTHOR_ID = B.AUTHOR_ID
#     GROUP BY A.BOOK_ID
#     ORDER BY A.BOOK_ID
# ) AS C
# JOIN(
#     SELECT BOOK_ID, SUM(SALES) AS CNT
#     FROM BOOK_SALES 
#     WHERE MONTH(SALES_DATE) = 1 AND YEAR(SALES_DATE) = 2022
#     GROUP BY BOOK_ID
#     ORDER BY BOOK_ID
# ) AS D 
# ON C.BOOK_ID = D.BOOK_ID
# GROUP BY CATEGORY
# ORDER BY AUTHOR_ID, CATEGORY DESC

SELECT A.AUTHOR_ID, B.AUTHOR_NAME, A.CATEGORY, SUM((PRICE*SALES)) AS TOTAL_SALES
FROM BOOK AS A
JOIN AUTHOR AS B ON A.AUTHOR_ID = B.AUTHOR_ID
JOIN BOOK_SALES AS C ON C.BOOK_ID = A.BOOK_ID
WHERE MONTH(C.SALES_DATE) = 1 AND YEAR(C.SALES_DATE) = 2022
GROUP BY A.CATEGORY, A.AUTHOR_ID
ORDER BY A.AUTHOR_ID, A.CATEGORY DESC