-- 코드를 입력하세요
SELECT USER_ID, PRODUCT_ID
FROM(
    SELECT USER_ID, PRODUCT_ID, COUNT(USER_ID AND PRODUCT_ID) as CNT
    FROM ONLINE_SALE
    GROUP BY USER_ID, PRODUCT_ID
    ORDER BY USER_ID ASC, PRODUCT_ID DESC
) a
WHERE CNT > 1 

# SELECT USER_ID, PRODUCT_ID
# FROM ONLINE_SALE
# # GROUP BY USER_ID, PRODUCT_ID
# ORDER BY USER_ID ASC,ONLINE_SALE_ID DESC